version: "3.8"
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:1.17.0"
    container_name: dynamoose
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -port 8000 -sharedDb"
